services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=questions_answers
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  db_for_test:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=questions_answers
    ports:
      - "5433:5432"
    volumes:
      - ./db_for_test/:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d admin" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build: .
#    volumes:
#      - ./app/:/app/
    depends_on:
      database:
        condition: service_healthy
        restart: true
    ports:
      - "8000:8000"