"""ondelete=CASCADE

Revision ID: 865d9febbe80
Revises: 9e37a27d8c85
Create Date: 2025-08-28 14:37:47.962867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "865d9febbe80"
down_revision: Union[str, Sequence[str], None] = "9e37a27d8c85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("answers_question_id_fkey"), "answers", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "answers",
        "questions",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("answers_question_id_fkey"),
        "answers",
        "questions",
        ["question_id"],
        ["id"],
    )
    # ### end Alembic commands ###
